### ISSUE TITLE
User Story: Site login and Logout

### ISSUE THREAD

**Issue by tamariam** [jamie33o/world-happiness-hackathon#4]
As a User I want  **to log in and log out **  so that I  ** can use all features of site**

#Acceptance Criteria
- As a registered user not currently signed in, upon visiting the login page and providing my credentials, I should be successfully logged into my account.
- As a logged-in user, when I choose to logout and confirm the request, the system should perform a successful logout, ending my current session.

Tasks: e.g. acceptable criteria for completion
- [ ]  Create login and logout functionality
- [ ]  create login and logout buttons.
- [ ]  create appropriate forms for login and logout
